import { ET, Task, User } from './types';

export const INITIAL_ETS: ET[] = [
  {
    id: 'et-1',
    name: 'A전자 기말감사',
    color: '#3B82F6',
    colorLight: '#EFF6FF',
  },
  {
    id: 'et-2',
    name: 'B건설 반기검토',
    color: '#F43F5E',
    colorLight: '#FFF1F2',
  },
  {
    id: 'et-3',
    name: 'C화학 PA',
    color: '#10B981',
    colorLight: '#ECFDF5',
  },
  {
    id: 'et-4',
    name: 'D물산 내부회계',
    color: '#8B5CF6',
    colorLight: '#F5F3FF',
  },
  {
    id: 'et-5',
    name: 'E바이오 IPO검토',
    color: '#F59E0B',
    colorLight: '#FFFBEB',
  },
  {
    id: 'et-6',
    name: 'F유통 기말감사',
    color: '#06B6D4',
    colorLight: '#ECFEFF',
  },
  {
    id: 'et-7',
    name: 'G금융 특수감사',
    color: '#EC4899',
    colorLight: '#FDF2F8',
  },
  {
    id: 'et-8',
    name: 'H에너지 반기검토',
    color: '#84CC16',
    colorLight: '#F7FEE7',
  },
  {
    id: 'et-9',
    name: 'I제약 기말감사',
    color: '#6366F1',
    colorLight: '#EEF2FF',
  },
  {
    id: 'et-10',
    name: 'J건설 내부회계',
    color: '#F97316',
    colorLight: '#FFF7ED',
  },
  {
    id: 'et-11',
    name: 'K전자 IFRS전환',
    color: '#14B8A6',
    colorLight: '#F0FDFA',
  },
  {
    id: 'et-12',
    name: 'L그룹 연결감사',
    color: '#DC2626',
    colorLight: '#FEF2F2',
  },
];

export const INITIAL_TASKS: Task[] = [
  // ── A전자 기말감사 (blue) · 멤버: 신관용(user-1), 김지수(user-2) ──
  {
    id: 'task-01',
    etId: 'et-1',
    assigneeId: 'user-1',
    title: '현금및현금성자산 명세서 작성',
    dueDate: '2026-05-02',
    status: 'Done',
    description: '기말 현금 잔액 명세서 작성 및 은행 잔액증명서 대사',
    timeBudget: 8,
    timeSpent: 7,
  },
  {
    id: 'task-02',
    etId: 'et-1',
    assigneeId: 'user-2',
    title: '은행조회서 발송',
    dueDate: '2026-05-07',
    status: 'Done',
    description: '주거래 은행 5개사 대상 조회서 발송 및 회신 관리',
    timeBudget: 4,
    timeSpent: 5,
  },
  {
    id: 'task-03',
    etId: 'et-1',
    assigneeId: 'user-1',
    title: '매출채권 차이조정',
    dueDate: '2026-05-14',
    status: 'In Progress',
    urgent: true,
    description: '외부조회 회신 결과와 장부 잔액 간 차이 원인 분석',
    timeBudget: 12,
    timeSpent: 6,
  },
  {
    id: 'task-04',
    etId: 'et-1',
    assigneeId: 'user-2',
    title: '재고실사 참여',
    dueDate: '2026-05-19',
    status: 'To-Do',
    description: '수원 물류센터 실사 참여 및 실사조서 작성',
    timeBudget: 8,
    timeSpent: 0,
  },
  {
    id: 'task-05',
    etId: 'et-1',
    assigneeId: 'user-1',
    title: 'IFRS 15 수익인식 검토',
    dueDate: '2026-05-26',
    status: 'To-Do',
    description: '반도체 장기공급계약 수행의무 식별 및 거래가격 배분 적정성 검토',
    timeBudget: 16,
    timeSpent: 0,
  },

  // ── B건설 반기검토 (rose) · 멤버: 김지수(user-2), 박서연(user-3) ─
  {
    id: 'task-06',
    etId: 'et-2',
    assigneeId: 'user-2',
    title: '공사수익 인식 검토',
    dueDate: '2026-05-06',
    status: 'Done',
    description: '진행기준 적용 현장별 공사진행률 산정 적정성 검토',
    timeBudget: 6,
    timeSpent: 6,
  },
  {
    id: 'task-07',
    etId: 'et-2',
    assigneeId: 'user-2',
    title: '특수관계자 거래 대조',
    dueDate: '2026-05-09',
    status: 'In Progress',
    urgent: true,
    description: '계열사 간 내부거래 내역 식별 및 시장가격 비교 분석',
    timeBudget: 8,
    timeSpent: 4,
  },
  {
    id: 'task-08',
    etId: 'et-2',
    assigneeId: 'user-3',
    title: '미완성주택 재고자산 실사',
    dueDate: '2026-05-15',
    status: 'To-Do',
    description: '인천 송도 현장 미완성주택 현장 확인 및 원가 집계 대사',
    timeBudget: 10,
    timeSpent: 0,
  },
  {
    id: 'task-09',
    etId: 'et-2',
    assigneeId: 'user-3',
    title: 'PF 우발채무 검토',
    dueDate: '2026-05-21',
    status: 'To-Do',
    description: '프로젝트파이낸싱 보증 현황 파악 및 충당부채 설정 적정성 검토',
  },
  {
    id: 'task-10',
    etId: 'et-2',
    assigneeId: 'user-2',
    title: '준공공사 정산 검토',
    dueDate: '2026-05-28',
    status: 'To-Do',
    description: '당기 준공 현장 최종 정산내역 검토 및 손익 귀속 적정성 확인',
  },

  // ── C화학 PA (emerald) · 멤버: 신관용(user-1), 박서연(user-3) ──────
  {
    id: 'task-11',
    etId: 'et-3',
    assigneeId: 'user-1',
    title: '영업권 손상 검토',
    dueDate: '2026-05-08',
    status: 'Done',
    description: '인수 사업부 현금창출단위 손상 징후 파악 및 회수가능액 산정 검토',
    timeBudget: 10,
    timeSpent: 9,
  },
  {
    id: 'task-12',
    etId: 'et-3',
    assigneeId: 'user-3',
    title: '취득원가 배분 (PPA) 작업',
    dueDate: '2026-05-13',
    status: 'In Progress',
    description: '유·무형자산 공정가치 평가 외부 전문가 보고서 검토',
    timeBudget: 16,
    timeSpent: 10,
  },
  {
    id: 'task-13',
    etId: 'et-3',
    assigneeId: 'user-1',
    title: '재고자산 평가 조정',
    dueDate: '2026-05-20',
    status: 'To-Do',
    description: '원재료·재공품·제품 단계별 저가법 평가 적정성 검토',
    timeBudget: 12,
    timeSpent: 0,
  },
  {
    id: 'task-14',
    etId: 'et-3',
    assigneeId: 'user-3',
    title: '환경부채 검토',
    dueDate: '2026-05-27',
    status: 'To-Do',
    description: '토양오염 복구 충당부채 추정 기초가정 합리성 검토',
  },

  // ── D물산 내부회계 (violet) · 멤버: 김지수(user-2), 박서연(user-3) ─
  {
    id: 'task-15',
    etId: 'et-4',
    assigneeId: 'user-2',
    title: 'ITGC 통제 테스트',
    dueDate: '2026-05-05',
    status: 'Done',
    description: 'ERP 접근통제·변경관리·운영통제 설계 및 운영 효과성 평가',
    timeBudget: 6,
    timeSpent: 7,
  },
  {
    id: 'task-16',
    etId: 'et-4',
    assigneeId: 'user-3',
    title: '재무보고 프로세스 평가',
    dueDate: '2026-05-12',
    status: 'In Progress',
    urgent: true,
    description: '결산·공시 프로세스 내 핵심통제 운영현황 평가',
    timeBudget: 12,
    timeSpent: 5,
  },
  {
    id: 'task-17',
    etId: 'et-4',
    assigneeId: 'user-2',
    title: 'IT 시스템 접근권한 검토',
    dueDate: '2026-05-22',
    status: 'To-Do',
    description: '퇴직자·직무변경자 접근권한 적시 회수 여부 확인',
    timeBudget: 8,
    timeSpent: 0,
  },
  {
    id: 'task-18',
    etId: 'et-4',
    assigneeId: 'user-3',
    title: '내부회계관리제도 운영현황 평가',
    dueDate: '2026-05-29',
    status: 'To-Do',
    description: '중요 업무프로세스별 통제 운영 증빙 검토 및 미비점 집계',
  },

  // ── E바이오 IPO검토 (amber) · 멤버: 신관용(user-1), 박서연(user-3) ─
  {
    id: 'task-19',
    etId: 'et-5',
    assigneeId: 'user-1',
    title: '매출 Cut-off 테스트',
    dueDate: '2026-05-03',
    status: 'Done',
    description: '기말 전후 출하기록·세금계산서 발행일 대사를 통한 기간귀속 검증',
    timeBudget: 4,
    timeSpent: 3,
  },
  {
    id: 'task-20',
    etId: 'et-5',
    assigneeId: 'user-3',
    title: '조세공과금 검토',
    dueDate: '2026-05-10',
    status: 'Review Clear 필요',
    description: '이연법인세 계산 적정성 및 세무조정 항목 검토',
    timeBudget: 8,
    timeSpent: 8,
  },
  {
    id: 'task-21',
    etId: 'et-5',
    assigneeId: 'user-1',
    title: 'R&D 비용 자본화 검토',
    dueDate: '2026-05-16',
    status: 'To-Do',
    description: '임상 2·3상 개발비 자본화 요건 충족 여부 및 상각 방법 적정성 검토',
    timeBudget: 10,
    timeSpent: 2,
  },
  {
    id: 'task-22',
    etId: 'et-5',
    assigneeId: 'user-3',
    title: '임상시험비 회계처리 검토',
    dueDate: '2026-05-23',
    status: 'To-Do',
    description: 'CRO 계약 기반 임상비용 발생주의 적용 및 선급금 정산 검토',
    timeBudget: 6,
    timeSpent: 0,
  },
  {
    id: 'task-23',
    etId: 'et-5',
    assigneeId: 'user-1',
    title: '주식기준보상 검토',
    dueDate: '2026-05-30',
    status: 'To-Do',
    description: '스톡옵션 공정가치 산정 모형(Black-Scholes) 및 가득조건 검토',
  },

  // ── F유통 기말감사 (cyan) · 멤버: 신관용(user-1), 박서연(user-3) ──
  {
    id: 'task-24',
    etId: 'et-6',
    assigneeId: 'user-1',
    title: '재고자산 실사 참여',
    dueDate: '2026-05-12',
    status: 'To-Do',
    description: '김포 물류센터 상품 실사 참여 및 실사조서 작성',
    timeBudget: 8,
    timeSpent: 0,
  },
  {
    id: 'task-25',
    etId: 'et-6',
    assigneeId: 'user-3',
    title: '매출 확인서 발송',
    dueDate: '2026-05-18',
    status: 'In Progress',
    description: '주요 거래처 20개사 대상 매출채권 외부확인 발송 및 회신 관리',
    timeBudget: 6,
    timeSpent: 3,
  },
  {
    id: 'task-26',
    etId: 'et-6',
    assigneeId: 'user-1',
    title: '상품매입 Cut-off 테스트',
    dueDate: '2026-05-27',
    status: 'To-Do',
    description: '기말 전후 입고기록과 세금계산서 수취일 대사를 통한 기간귀속 검증',
    timeBudget: 5,
    timeSpent: 0,
  },

  // ── G금융 특수감사 (pink) · 멤버: 김지수(user-2), 박서연(user-3) ──
  {
    id: 'task-27',
    etId: 'et-7',
    assigneeId: 'user-2',
    title: '금융상품 공정가치 평가 검토',
    dueDate: '2026-05-14',
    status: 'To-Do',
    description: 'Level 2·3 금융상품 외부평가기관 보고서 적정성 검토',
    timeBudget: 10,
    timeSpent: 0,
  },
  {
    id: 'task-28',
    etId: 'et-7',
    assigneeId: 'user-3',
    title: 'AML 내부통제 평가',
    dueDate: '2026-05-22',
    status: 'To-Do',
    description: '자금세탁방지 프로세스 설계·운영 효과성 평가 및 취약점 보고',
    timeBudget: 12,
    timeSpent: 0,
  },

  // ── H에너지 반기검토 (lime) · 멤버: 신관용(user-1), 박서연(user-3) ──
  {
    id: 'task-29',
    etId: 'et-8',
    assigneeId: 'user-1',
    title: '원가명세서 검토',
    dueDate: '2026-05-11',
    status: 'In Progress',
    urgent: true,
    description: '제조원가명세서 항목별 전기 대비 증감 분석 및 이상치 검토',
    timeBudget: 8,
    timeSpent: 5,
  },
  {
    id: 'task-30',
    etId: 'et-8',
    assigneeId: 'user-3',
    title: '유형자산 내역 검토',
    dueDate: '2026-05-25',
    status: 'To-Do',
    description: '발전설비 자본적지출·수익적지출 구분 적정성 및 감가상각 검토',
    timeBudget: 10,
    timeSpent: 0,
  },

  // ── I제약 기말감사 (indigo) · 멤버: 신관용(user-1), 김지수(user-2) ──
  {
    id: 'task-31',
    etId: 'et-9',
    assigneeId: 'user-1',
    title: '임상비용 회계처리 검토',
    dueDate: '2026-05-16',
    status: 'To-Do',
    description: 'CRO 계약 기반 단계별 임상비 발생주의 적용 및 선급금 정산 검토',
    timeBudget: 8,
    timeSpent: 0,
  },
  {
    id: 'task-32',
    etId: 'et-9',
    assigneeId: 'user-2',
    title: '특수관계자 거래 검토',
    dueDate: '2026-05-23',
    status: 'To-Do',
    description: '계열 제조사 간 원료 공급 내부거래 시장가격 비교 및 공시 적정성 검토',
    timeBudget: 6,
    timeSpent: 0,
  },

  // ── J건설 내부회계 (orange) · 멤버: 김지수(user-2), 박서연(user-3) ──
  {
    id: 'task-33',
    etId: 'et-10',
    assigneeId: 'user-2',
    title: 'IT 접근통제 테스트',
    dueDate: '2026-05-19',
    status: 'To-Do',
    description: 'ERP 시스템 접근권한 설정 및 권한 분리 운영 효과성 평가',
    timeBudget: 6,
    timeSpent: 0,
  },
  {
    id: 'task-34',
    etId: 'et-10',
    assigneeId: 'user-3',
    title: '공사원가 프로세스 평가',
    dueDate: '2026-05-27',
    status: 'To-Do',
    description: '현장별 원가집계 프로세스 핵심통제 운영현황 평가 및 미비점 집계',
    timeBudget: 10,
    timeSpent: 0,
  },

  // ── K전자 IFRS전환 (teal) · 멤버: 김지수(user-2), 박서연(user-3) ──
  {
    id: 'task-35',
    etId: 'et-11',
    assigneeId: 'user-2',
    title: 'IFRS 16 리스 전환 검토',
    dueDate: '2026-05-20',
    status: 'In Progress',
    urgent: true,
    description: '운용리스 사용권자산·리스부채 최초 인식 계산 적정성 검토',
    timeBudget: 14,
    timeSpent: 8,
  },
  {
    id: 'task-36',
    etId: 'et-11',
    assigneeId: 'user-3',
    title: '비교재무제표 재작성 검토',
    dueDate: '2026-05-28',
    status: 'To-Do',
    description: 'K-GAAP → IFRS 전환 조정사항 반영 비교 재무제표 정합성 검토',
    timeBudget: 12,
    timeSpent: 0,
  },

  // ── L그룹 연결감사 (red) · 멤버: 박서연(user-3) ─────────────────
  {
    id: 'task-37',
    etId: 'et-12',
    assigneeId: 'user-3',
    title: '연결조정분개 검토',
    dueDate: '2026-05-17',
    status: 'In Progress',
    description: '종속회사 내부거래 상계 및 미실현손익 제거 조정분개 적정성 검토',
    timeBudget: 16,
    timeSpent: 7,
  },
  {
    id: 'task-38',
    etId: 'et-12',
    assigneeId: 'user-3',
    title: '내부거래 상계 검토',
    dueDate: '2026-05-24',
    status: 'To-Do',
    description: '그룹 내 자금 대차·배당 거래 상계표 작성 및 연결 조정 완전성 검토',
    timeBudget: 10,
    timeSpent: 0,
  },
];

// ── Mock Users ────────────────────────────────────────────────────────────────
//
// Each user is assigned to a subset of ETs.  Tasks belong to the ET, not the
// user — two members of the same ET see identical tasks for that ET, but each
// user's "unified view" is scoped to their own assignment list.

export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    name: '신관용',
    role: 'A2',
    // A전자·C화학·E바이오·F유통·H에너지·I제약  (6 ETs)
    assignedEtIds: ['et-1', 'et-3', 'et-5', 'et-6', 'et-8', 'et-9'],
  },
  {
    id: 'user-2',
    name: '김지수',
    role: 'SA1',
    // A전자·B건설·D물산·G금융·I제약·J건설·K전자  (7 ETs)
    assignedEtIds: ['et-1', 'et-2', 'et-4', 'et-7', 'et-9', 'et-10', 'et-11'],
  },
  {
    id: 'user-3',
    name: '박서연',
    role: 'SM1',
    // B건설·C화학·D물산·E바이오·F유통·G금융·H에너지·K전자·L그룹  (9 ETs)
    assignedEtIds: ['et-2', 'et-3', 'et-4', 'et-5', 'et-6', 'et-7', 'et-8', 'et-11', 'et-12'],
  },
];

export const DEFAULT_USER = MOCK_USERS[0];
